[package]
name = "nexus"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Nexus CLI."

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "env"] }
nexusd = { path = "../daemon" }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40", features = ["full"] }
urlencoding = "2.1"

